#!/bin/bash

ROUTES_FILE="routes.yml"
OUTPUT_DIR="traefik/dynamic"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Remove all files in OUTPUT_DIR that don't start with underscore
find "$OUTPUT_DIR" -type f ! -name '_*' -delete

# Get the length of the array
length=$(yq 'length' "$ROUTES_FILE")

# Iterate through each entry
for ((i=0; i<$length; i++)); do
    name=$(yq ".[$i].name" "$ROUTES_FILE")
    domains=$(yq ".[$i].domains" "$ROUTES_FILE")
    urls=$(yq ".[$i].urls" "$ROUTES_FILE")

    # Process domains: split by comma, trim spaces, and format for Traefik
    formatted_domains=""
    IFS=',' read -ra DOMAIN_ARRAY <<< "$domains"
    for domain in "${DOMAIN_ARRAY[@]}"; do
        # Trim whitespace and append to formatted string
        domain=$(echo "$domain" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        if [ -z "$formatted_domains" ]; then
            formatted_domains="\`$domain\`"
        else
            formatted_domains="$formatted_domains, \`$domain\`"
        fi
    done

    # Process URLs and format them for the output
    formatted_urls=""
    IFS=',' read -ra URL_ARRAY <<< "$urls"
    for url in "${URL_ARRAY[@]}"; do
        # Trim whitespace
        url=$(echo "$url" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
        formatted_urls+="          - url: \"$url\""$'\n'
    done

    # Remove the last newline from formatted_urls
    formatted_urls=${formatted_urls%$'\n'}

    # Create the base configuration
    cat > "$OUTPUT_DIR/$name.yml" << EOF
# Do not edit this file directly,
# Edit routes.yml to modify these settings
http:
  routers:
    $name:
      rule: "Host($formatted_domains)"
      entryPoints:
        - websecure
      service: $name
  services:
    $name:
      loadBalancer:
        servers:
$formatted_urls
EOF

    # If any URL starts with https://, add serversTransport
    if [[ "$urls" == *https* ]]; then
        echo "        serversTransport: insecureSkipVerifyTransport" >> "$OUTPUT_DIR/$name.yml"
    fi
done

# Only stage the changes, let git handle the commit
git add "$OUTPUT_DIR"
