#!/bin/bash

ROUTES_FILE="routes.yml"
OUTPUT_DIR="traefik/dynamic"

# Create output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Remove all files in OUTPUT_DIR that don't start with underscore
find "$OUTPUT_DIR" -type f ! -name '_*' -delete

# Get the length of the array
length=$(yq 'length' "$ROUTES_FILE")

# Iterate through each entry
for ((i=0; i<$length; i++)); do
    name=$(yq ".[$i].name" "$ROUTES_FILE")
    domain=$(yq ".[$i].domain" "$ROUTES_FILE")
    url=$(yq ".[$i].url" "$ROUTES_FILE")

    # Create the base configuration
    cat > "$OUTPUT_DIR/$name.yml" << EOF
# Do not edit this file directly,
# Edit routes.yml to modify these settings
http:
  routers:
    $name:
      rule: "Host(\`$domain\`)"
      entryPoints:
        - websecure
      service: $name
  services:
    $name:
      loadBalancer:
        servers:
          - url: "$url"
EOF

    # If URL starts with https://, add serversTransport
    if [[ "$url" == https://* ]]; then
        echo "        serversTransport: insecureSkipVerifyTransport" >> "$OUTPUT_DIR/$name.yml"
    fi
done

# Only stage the changes, let git handle the commit
git add "$OUTPUT_DIR"
