http:
  routers:
    bazarr:
      rule: "Host(`bazarr.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: bazarr
  services:
    bazarr:
      loadBalancer:
        servers:
          - url: "http://10.10.0.102:6767"
