http:
  routers:
    download:
      rule: "Host(`download.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: download
  services:
    download:
      loadBalancer:
        servers:
          - url: "http://10.10.0.102:8077"
