http:
  routers:
    grafana:
      rule: "Host(`grafana.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: grafana
  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://10.10.0.108:3000"
