http:
  routers:
    homarr:
      rule: "Host(`lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: homarr
  services:
    homarr:
      loadBalancer:
        servers:
          - url: "http://10.10.0.102:7575"
