http:
  routers:
    homebridge:
      rule: "Host(`homebridge.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: homebridge
  services:
    homebridge:
      loadBalancer:
        servers:
          - url: "http://10.10.0.105:8581"
