http:
  routers:
    lidarr:
      rule: "Host(`lidarr.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: lidarr
  services:
    lidarr:
      loadBalancer:
        servers:
          - url: "http://10.10.0.102:8686"
