http:
  routers:
    litellm:
      rule: "Host(`litellm.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: litellm
  services:
    litellm:
      loadBalancer:
        servers:
          - url: "http://10.10.0.102:4000"
