http:
  routers:
    metube:
      rule: "Host(`metube.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: metube
  services:
    metube:
      loadBalancer:
        servers:
          - url: "http://10.10.0.102:8081"
