http:
  routers:
    photos:
      rule: "Host(`photos.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: photos
  services:
    photos:
      loadBalancer:
        servers:
          - url: "http://10.10.0.149:2283"
