http:
  routers:
    portainer:
      rule: "Host(`portainer.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: portainer
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://10.10.0.102:9443"
        serversTransport: insecureSkipVerifyTransport
