http:
  routers:
    prx1:
      rule: "Host(`prx1.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: prx1
  services:
    prx1:
      loadBalancer:
        servers:
          - url: "https://192.168.2.150:8006"
        serversTransport: insecureSkipVerifyTransport
