http:
  routers:
    radarr:
      rule: "Host(`radarr.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: radarr
  services:
    radarr:
      loadBalancer:
        servers:
          - url: "http://10.10.0.102:7878"
