http:
  routers:
    wallos:
      rule: "Host(`wallos.lab.ehcan.io`)"
      entryPoints:
        - websecure
      service: wallos
  services:
    wallos:
      loadBalancer:
        servers:
          - url: "http://10.10.0.102:8282"
